language: c

dist: trusty	

compiler:
  - clang
  - gcc

before_install:
- sudo apt-get update
- echo "deb [trusted=yes] https://nexus.fd.io/content/repositories/fd.io.stable.1801.ubuntu.trusty.main/ ./" | sudo tee -a /etc/apt/sources.list.d/99fd.io.list
- sudo apt-get update 
- sudo apt-get install -y vpp vpp-lib vpp-dev vpp-plugins vpp-api-python python-cffi autoconf libtool ethtool

script: cd mmb-plugin; autoreconf -fis; ./configure && make && make test

